# used only in local testing
services:
  traefik:
    profiles:
      - disabled
  n8n:
    # Explicitly clear all labels for the n8n service
    labels: 
       - "traefik.enable=false"
       - "traefik.http.routers.n8n.tls.certresolver="
      