[project]
name = "property_agent"
version = "0.1.0"
description = "Answer questions related to Vertex AI documentation using Vertex AI RAG Engine"
authors = []

license = "Apache License 2.0"
readme = "README.md"
dependencies = [
    "adk>=0.0.5",
    "google-adk>=1.17.0",
    "langchain>=1.0.2",
    "langchain-community>=0.4",
    "tool>=0.8.0",
    "tools>=1.0.6",
]

[tool.poetry.dependencies]
python = "^3.11"
pydantic-settings = "^2.8.1"
tabulate = "^0.9.0"
google-auth = "^2.36.0"
requests = "^2.32.3"
google-adk = "1.7.0"
google-cloud-aiplatform = { extras = [
        "adk",
        "agent-engines",
], version = "1.104.0" }
llama-index = "^0.12"
google-cloud-pubsub = "^2.31.1"
langchain-community = "^0.3.27"
youtube-search = "^2.1.2"
google-search-results = "^2.4.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-mock = "^3.14.0"
scikit-learn = "^1.6.1"
pytest-cov = "^6.0.0"
pytest-asyncio = "^0.26.0"
black = "^25.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
