name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (demo, staging, prod)'
        required: true
        default: 'demo'
        type: choice
        options:
          - demo
          - staging
          - prod
jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Validate Environment
        id: validate-env
        run: |
          if [[ "${{ github.event.inputs.environment }}" =~ ^(demo|staging|prod)$ ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
            echo "instance_name=${{ vars.GCP_INSTANCE_ID_PREFIX }}${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "Invalid environment: ${{ github.event.inputs.environment }}"
            exit 1
          fi
      - name: Set uppercase environment
        run: echo "ENV_UPPER=$(echo ${{ github.event.inputs.environment }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[format('GCP_SA_KEY_{0}', env.ENV_UPPER)] }}
          export_environment_variables: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'beta'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
        
      - name: Terraform Init with Backend
        run: terraform init -backend-config="bucket=${{ vars.GCS_BACKEND_BUCKET }}" -backend-config="prefix=terraform/${{ env.environment }}" -lock=true
        working-directory: deployment/terraform
    
      - name: Copy and Execute Backup Script
        run: |
          gcloud compute scp scripts/backup-volumes.sh ${{ env.instance_name }}:/tmp/backup-volumes.sh --zone=${{ vars.GCP_ZONE }}
          gcloud compute ssh ${{ env.instance_name }} --zone=${{ vars.GCP_ZONE }} --command="
            sudo chmod +x /tmp/backup-volumes.sh
            sudo -u deploy /tmp/backup-volumes.sh ${{ vars.GCS_BACKEND_BUCKET }} ${{ env.environment }}
            sudo rm /tmp/backup-volumes.sh
          "
      
      - name: Terraform Destroy
        env:
          TF_VAR_environment: ${{ env.environment }}
          TF_VAR_instance_name: ${{ env.instance_name }}
          TF_VAR_zone: ${{ vars.GCP_ZONE }}
          TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ vars.GCP_REGION }}
          TF_VAR_tags: ${{ env.instance_name }}
          TF_VAR_GCS_BACKEND_BUCKET: ${{ vars.GCS_BACKEND_BUCKET }}
        run: terraform destroy -auto-approve
        working-directory: deployment/terraform