name: Stream Instance Logs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - demo
          - staging
          - prod
  push:
    branches:
      - restore_docker_volumes
    paths:
      - 'deployment/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  stream-logs:
    name: Stream Instance Logs
    runs-on: ubuntu-latest
    steps:
      # Set default environment for push events
      - name: Set Default Environment
        if: github.event_name == 'push'
        run: |
          echo "environment=demo" >> $GITHUB_ENV

      # Use workflow input for manual triggers
      - name: Set Input Environment
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          echo "instance_name=${{ vars.GCP_INSTANCE_ID_PREFIX }}${{ env.environment }}" >> $GITHUB_ENV
          echo "ENV_UPPER=$(echo ${{ env.environment }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
        
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[format('GCP_SA_KEY_{0}', env.ENV_UPPER)] }}
          export_environment_variables: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'beta'

      - name: Set Log Path
        run: echo "STARTUP_LOG=/home/deploy/startup_script.log" >> $GITHUB_ENV

      - name: Stream Startup Script Log
        if: always()
        run: |
          # Create a minimal monitoring script
          gcloud compute ssh ${{ env.instance_name }} --zone=${{ vars.GCP_ZONE }} --command='
          cat << EOF > /tmp/monitor.sh
          #!/bin/bash
          log_file=$1
          while ! grep "Startup script execution completed" $log_file &>/dev/null; do
            tail -n 20 $log_file
            sleep 30
          done
          cat $log_file
          EOF
          ' || exit 1

          # Make script executable and run it
          gcloud compute ssh ${{ env.instance_name }} --zone=${{ vars.GCP_ZONE }} --command="
          sudo chmod +x /tmp/monitor.sh && 
          sudo -u deploy /tmp/monitor.sh ${{ env.STARTUP_LOG }} &&
          sudo rm /tmp/monitor.sh"