name: Stream Instance Logs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - demo
          - staging
          - prod
  push:
    branches:
      - restore_docker_volumes
    paths:
      - 'deployment/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  stream-logs:
    name: Stream Instance Logs
    runs-on: ubuntu-latest
    steps:
      # Set default environment for push events
      - name: Set Default Environment
        if: github.event_name == 'push'
        run: |
          echo "environment=demo" >> $GITHUB_ENV

      # Use workflow input for manual triggers
      - name: Set Input Environment
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          echo "instance_name=${{ vars.GCP_INSTANCE_ID_PREFIX }}${{ env.environment }}" >> $GITHUB_ENV
          echo "ENV_UPPER=$(echo ${{ env.environment }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
        
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[format('GCP_SA_KEY_{0}', env.ENV_UPPER)] }}
          export_environment_variables: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'beta'

      - name: Set Log Path
        run: echo "STARTUP_LOG=/home/deploy/startup_script.log" >> $GITHUB_ENV

      - name: Stream Startup Script Log
        if: always()
        run: |
          echo "Waiting for startup script to complete..."
          attempt=1
          max_attempts=20
          until gcloud compute ssh ${{ env.instance_name }} --zone=${{ vars.GCP_ZONE }} --command="sudo grep 'Startup script execution completed' ${{ env.STARTUP_LOG }}" &>/dev/null || [ $attempt -gt $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts:"
            gcloud compute ssh ${{ env.instance_name }} \
              --zone=${{ vars.GCP_ZONE }} \
              --command="sudo tail -n 20 ${{ env.STARTUP_LOG }}"
            sleep 30
            ((attempt++))
          done

          if [ $attempt -gt $max_attempts ]; then
            echo "Timeout waiting for startup script to complete. Last few lines of log:"
            gcloud compute ssh ${{ env.instance_name }} \
              --zone=${{ vars.GCP_ZONE }} \
              --command="sudo tail -n 50 ${{ env.STARTUP_LOG }}"
            exit 1
          else
            echo "Startup script completed successfully. Full log:"
            gcloud compute ssh ${{ env.instance_name }} \
              --zone=${{ vars.GCP_ZONE }} \
              --command="sudo cat ${{ env.STARTUP_LOG }}"
          fi