name: Update GCP VM

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (demo, staging, prod)'
        required: true
        default: 'demo'
        type: choice
        options:
          - demo
          - staging
          - prod
      zone:
        description: "GCP zone where the VM is located (e.g., us-central1-a)"
        required: true
        default: "us-central1-a"

jobs:
  update-vm:
    name: Update GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Create credentials.json
        run: echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ${{ github.workspace }}/credentials.json

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/zone us-central1-a

      - name: Deploy App via SSH
        run: |
          gcloud compute ssh 'homegeek${{ github.event.inputs.environment }}' \
            --command="cd /HomeAMA && cp .env.${{ github.event.inputs.environment }} .env && git pull origin main && docker-compose down && docker compose up -d"